### PR TITLE
Pine script language updates

### PR DESCRIPTION
**Pull request by darrylhebbes**
Adds new `table` features and a few other unannounced changes 
Bumps version

@EricCrosson I tried controlling the formatting in the changes but somehow I could not. The `table` changes are not yet announced on the blog.

### CODE REVIEW

**Comment by darrylhebbes** [comment]
Related news : https://www.tradingview.com/blog/en/introducing-pine-tables-24604/

**Comment by EricCrosson** [comment]
> Related news : [tradingview.com/blog/en/introducing-pine-tables-24604](https://www.tradingview.com/blog/en/introducing-pine-tables-24604/)

Wild!

**Comment by EricCrosson** [comment]
The changes look good to me, aside from that merge conflict :+1:

**Comment by EricCrosson** [comment]
@darrylhebbes , I invited you to be a collaborator of this repository. I don't want to slow down your progress and you're more involved in the growth of this package than I am right now. 

Thank you for your consistent high-quality upstream contributions

**Comment by darrylhebbes** [comment]
Thanks @EricCrosson , I appreciate the love ;-)

Thanks for making me a contributor, I will get going with all the other mode features I think we need. I will make a TODO list in the README.

Also may I update the screenshot to reflect newer pine-script-mode features? I will use relevant pine code and a theme that is contrast acceptable.

**Comment by EricCrosson** [comment]
> Also may I update the screenshot to reflect newer pine-script-mode features? I will use relevant pine code and a theme that is contrast acceptable.

Sounds like a great idea. Every time I check out the readme that picture haunts me :sweat_smile:

**Comment by darrylhebbes** [comment]
Haha, ok cool.

**Pull request merged**
